file:
  client-path: /file
  storage-location: D:\ISTAD\ite-file-upload/
  base-uri:  http://localhost:8080${file.client-path}/

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/ite_ecommerce
    username: postgres
    password: qwer
  application:
    name: ecommerce-ite
